Fix build with gcc-12
:Release Notes:
Fixes:
http://gecko.lge.com/Errors/Details/401124

:Detailed Notes:
FAILED: test/CMakeFiles/test_jsonparser.dir/test_jsonparser.cpp.o
TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/recipe-sysroot-native/usr/bin/arm-oemllib32-linux-gnueabi/arm-oemllib32-linux-gnueabi-g++  -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/src -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/include/public/ls2-helpers -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/include/public -isystem TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/src/gtest/include -isystem TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/src/gtest -mthumb -mfpu=neon -mfloat-abi=softfp -mcpu=cortex-a9 -mtune=cortex-a9 -funwind-tables -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0=/usr/src/debug/lib32-ls2-helpers/1.0.0-10-r0                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0=/usr/src/debug/lib32-ls2-helpers/1.0.0-10-r0                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++11 -Wall -Wextra -fno-permissive -Wno-unused-parameter -Wno-type-limits, -Wno-missing-field-initializers -Werror=return-type -Werror=reorder -Werror=uninitialized -Wl,--no-undefined -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/lib/glib-2.0/include -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/lib32-recipe-sysroot/usr/lib/glib-2.0/include -DNDEBUG -MD -MT test/CMakeFiles/test_jsonparser.dir/test_jsonparser.cpp.o -MF test/CMakeFiles/test_jsonparser.dir/test_jsonparser.cpp.o.d -o test/CMakeFiles/test_jsonparser.dir/test_jsonparser.cpp.o -c TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/test/test_jsonparser.cpp
TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/test/test_jsonparser.cpp: In member function 'virtual void TestJsonParser_JsonParserValueMapTest_Test::TestBody()':
TOPDIR/BUILD/work/MACH-oemllib32-linux-gnueabi/lib32-ls2-helpers/1.0.0-10-r0/git/test/test_jsonparser.cpp:525:47: error: variable 'std::array<std::pair<int, std::__cxx11::basic_string<char> >, 2> INT_ARRAY' has initializer but incomplete type
  525 |         std::array<std::pair<int, string>, 2> INT_ARRAY {{{0, "zero"}, {1234, "many"}}};
      |                                               ^~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-10791] CCC: Various build fixes

Change-Id: I734d7cb56250e40bd3adbbb424d9094b84058fd2